### PR TITLE
ParkSmart Updated Parking Lot

### PR DESCRIPTION
**Pull request by semayashar**
Updated CSS and JS for the parking lot.

### CODE REVIEW

**Review by sonerkochan — CHANGES_REQUESTED** [review]
Dear Sema Yasharova,

It appears that the file `parkinglot.jpg` is not being used in our application. Kindly remove it before we approve your commit.

Thank you for your attention to this matter.

Best regards,
Soner Kochan

**Review by sonerkochan — CHANGES_REQUESTED** [review]
Dear Sema Yasharova,

I hope this message finds you well.

I would like to request a change to the script filename to script.js. Currently, the file is not functioning as intended because Visual Studio is recognizing it as a TypeScript file rather than a JavaScript file. This misinterpretation can lead to issues in executing the script, as TypeScript requires specific compilation steps that are not applicable to regular JavaScript.

Renaming the file to script.js will resolve this issue and ensure that the script runs correctly within our application.

Thank you for your understanding and prompt attention to this matter.

Best regards,
Soner Kochan

**Comment by semayashar** [comment]
Dear Soner Kochan,

I hope you're doing well.

I have made the necessary corrections to the HTML and CSS files as requested. However, I did not remove the "parkinglot.jpg" file, as it is the main image for our site and will be needed in the future. 
Please let me know if you'd like to discuss any further adjustments regarding this.

Thank you for your understanding.

Best regards,  
Sema Yasharova

**Comment by sonerkochan** [comment]
Thank you for making the changes to the HTML and CSS files. I'm glad with the adjustments you’ve made, and I understand the importance of keeping the "parkinglot.jpg" for future use. No further adjustments are needed at the moment.

Thanks again for your attention to detail.

Best regards

**Pull request merged**
